### ISSUE TITLE
B2B-Staging Deployment Failing, maven out of memory

### ISSUE THREAD

**Issue by jlhughes** [nanoPayinc/nanopay-tools#3]
There is insufficient memory for the Java Runtime Environment to continue.
[stderr]OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000fe200000, 31457280, 0) failed; error='Cannot allocate memory' (errno=12)
[stdout]# Native memory allocation (mmap) failed to map 31457280 bytes for committing reserved memory.
[stdout]# An error report file with more information is saved as:
[stdout]# /pkg/stack/stage/NANOPAY/hs_err_pid949.log

**Comment by jlhughes** [comment]
CC-Staging is deploying successfully.

**Comment by pakkiraju** [comment]
You can fix this by rebooting the b2b-staging environment through AWS

**Comment by jlhughes** [comment]
Resolved with reboot.  Will have to investigate the memory leak.
