### ISSUE TITLE
clustering / failover / live deployment

### ISSUE THREAD

**Issue by jlhughes** [nanoPayinc/nanopay-tools#9]
Version 3 - FileLock
Scenario

* One Journal with all operations interleaved.
* Journal on NFS 

All instances in 'cluster' attempt to acquire NFS File Lock
Those without the lock (SLAVE):
* tail the journal keeping MDAOs up-to-date
* NOT process transactions
* DIG/DUG enabled for all but transaction processing (how ensure only one replies)
* Enable Web UI

Instance with lock (MASTER):
* append to journal
* process transactions
* DIG/DUG disabled except for transaction processing
* Disable Web UI - to all but 'admin'

Issues
* DIG/DUG - how to only get one DUG response, may have be handled by MASTER

Additional
* AppConfig - control mode (MASTER, SLAVE)
* Repo journal.0 files must be packaged by build and stored in jar as jar will be signed.

Security
* PKI - all instances have same keys?  Does anything in a signed transaction need to be decrypted?

**Comment by jlhughes** [comment]
Thoughts:
Use DUG to create clustering.  This handles fail-over, which could be the same case as an upgrade as we upgrade one half at a time. 
So how does clustering discovery work

- each instance sends UDP ping with AppConfig.
- instances will connect to each other  
how do we handle sync
- have to request/send all changes since some date, and the instance cannot handle traffic until it's in sync.

**Comment by jlhughes** [comment]
Version 2 - Simplified
Scenario
* 3 instances x, y, z
* all share nas/raid file system
* on startup 
  * if acquire lock, then master
    * process transactions
    * disable non-admin web interface and non-txn dig 
  * no lock, then slave
    * ignore transactions
    * enable regular web, dig 
* all continually try to get lock. 
  * when instance acquires lock it doesn't read all journals, 
    * it reads appropriate journal path to determine user balance

**Comment by ronin00** [comment]
Issue moved to JIRA: https://nanopay.atlassian.net/browse/DOP-54
